### PR TITLE
Package vulnerability fix

### PR DESCRIPTION
**Pull request by ifahadashraf**
**Description:** Vulnerable packages updated

**Ticket Link:** https://edlyio.atlassian.net/browse/EDE-554

Npm provides a cli command for application audit and auto fix
`npm audit fix`

### CODE REVIEW

**Review by danialmalik — APPROVED** [review]
Since we cannot review the package-lock.json file, I am hoping that you've tested the things from your end.
Also, there isn't a single change in `package.json` file?

**Review by imhassantariq — APPROVED** [review]

**Review by HamzaIbnFarooq — APPROVED** [review]

**Comment by tasawernawaz** [comment]
@ifahadashraf you have to update `packege.json` and then run `npm install`, it will automatically update `package-lock.json`

**Comment by tasawernawaz** [comment]
also please deploy this to stage and test that theme is working fine before we can merge this.

**Comment by ifahadashraf** [comment]
> Since we cannot review the package-lock.json file, I am hoping that you've tested the things from your end.
> Also, there isn't a single change in `package.json` file?

@danialmalik You can view the change but you have to explicitly clicl 'Load diff'. Only then you'll be able to see the changes.
Package.json needs no change as acorn and other updated packages are not directly used in code but used by 3rd party packages. That's why they are listed only in package-lock.json.

We can reinstall the package using both these Vulnerable packages and it will reinstalled all dependent packages as well.

**Comment by ifahadashraf** [comment]
@tasawernawaz I don't think we need to test on a deployment server as these packages are part of a dev dependency and it will not be included in the final build. So I guess we're good here.

**Comment by tasawernawaz** [comment]
> Package.json needs no change as acorn and other updated packages are not directly used in code but used by 3rd party packages. That's why they are listed only in package-lock.json.

I think the case recommended way is to update the 3rd party packages. Updating directly in `package-lock.json` may break other dependent things.

> @tasawernawaz I don't think we need to test on a deployment server as these packages are part of a dev dependency and it will not be included in the final build. So I guess we're good here.

In this case, I would ask someone to test changes on their local.

**Pull request merged**
